### ISSUE TITLE
Windows 10 2004，19041.21 好像无法使用

### ISSUE THREAD

**Issue by oneHTZ** [Albert-W/Folder-locker#10]
![Snipaste_2020-01-16_10-51-24](https://user-images.githubusercontent.com/44291833/72489148-281fd200-384e-11ea-92d2-3c09780722e3.png)

加密后直接显示.{2559a1f2-21d7-11d4-bdaf-00c04f60b9f0}，右键删除加密即失效

**Comment by Albert-W** [comment]
图标是对的，后缀显示出来了。可以取消显示后缀吗？
Windows 10 2004，19041.21 是最新的系统，之前的系统能使用吗？
如果能，试试全部解锁之后，卸载重装。

**Comment by Albert-W** [comment]
1.3.0 提升了软件的稳定性，建议试一试。
