### ISSUE TITLE
無法安裝，報錯

### ISSUE THREAD

**Issue by natsumehowe** [Albert-W/Folder-locker#11]
打開安裝包後即顯示「The folder path 'Program Files’ contains an invalid character」
我的電腦上共有C(SSD，win10系統）、D（光驅）、E（HDD，通常是安裝軟件和遊戲的分區，我自建有Program Files目錄）、F（同上一個HDD，安裝有另外一個Windows系統）四個磁盤分區

**Comment by Albert-W** [comment]
可以试试不使用默认的安装路径，在E盘安装试试。

**Comment by natsumehowe** [comment]
![捕获](https://user-images.githubusercontent.com/29534442/73518002-1fc3bb80-4438-11ea-993b-cab354902546.PNG)
![捕获0](https://user-images.githubusercontent.com/29534442/73518008-23574280-4438-11ea-8b2a-977bfab1053c.PNG)
并沒有選擇路徑的情況，打開直接是報錯界面

**Comment by jmk92** [comment]
我也遇到了，我的系统没有D盘，只有C盘，也是这个错误。
建议：在出现这个错误的时候，切换到C盘路径一下重复执行一下。

**Comment by zhz1237ok** [comment]
> 可以试试不使用默认的安装路径，在E盘安装试试。

软件一打开就默认自动安装了，没有选择的余地，所以遇到默认路径有空格的会弹出这个错误提示
希望增加一个安装前选择路径的功能

**Comment by shadow1163** [comment]
遇到了一样的错误

**Comment by shadow1163** [comment]
加了个D盘之后，才能选择安装位置，建议默认路径还是使用默认的C盘。
![image](https://user-images.githubusercontent.com/8413967/81469835-d7c3ea00-9219-11ea-910b-f6875512c4e6.png)

**Comment by Albert-W** [comment]
你好，1.3.0提升了稳定性，可以试试。
