### ISSUE TITLE
忘记密码打不开了

### ISSUE THREAD

**Issue by 42-0p6180339887** [Albert-W/Folder-locker#18]
我不觉得是密码错了，我把加密之后的文件拖到另一个硬盘了，然后解密的时候提示我password is missing，按照大佬的方法运行命令行，只有报错，卸载了之后文件夹还是锁着，只好又下了回来，然后发现另外的也都提示password missing了。。。
完全不懂编程，只是觉得您这个软件真好用就拿来用了，结果遇到了这些问题。
希望大佬帮忙 😥

**Comment by Albert-W** [comment]
你试试使用everything 找到文件，并全部复制出来。

**Comment by 42-0p6180339887** [comment]
> 你试试使用everything 找到文件，并全部复制出来。
谢谢你的建议，不过因为是照片文件夹，所以并不记得内部的文件名。目前已经解决。看到前边有说cmd改后缀的，我没有成功。我是用PowerToys中的重命名把后缀去掉了。Quicker的动作"修改后缀名"也可以解决。
接下来还会继续支持。谢谢。

**Comment by JonYou03** [comment]
下载个diskgenius工具 在里面复制出来

**Comment by Albert-W** [comment]
在1.3.0 版本中，我增加了通用密码 Albert-W

**Comment by Leoironk** [comment]
我发现一个方法：随便新建一个文件，例如新建一个文件名为hello的文件，加密一下他，密码为world，然后把他随便重命名一下，再把忘记密码的文件夹重命名为hello，这样就可以用密码world解锁了
