### ISSUE TITLE
破解方法

### ISSUE THREAD

**Issue by XiangZhi1998** [Albert-W/Folder-locker#25]
win10右键选择——发送到——压缩(zipped)文件夹，压缩完成后不解压，用压缩软件直接打开就能够获取文件了，有没有办法解决？
![加密_ev](https://user-images.githubusercontent.com/50309916/104167292-122ff780-5437-11eb-9243-07a1b2997007.gif)

**Comment by Albert-W** [comment]
可能挺有才的。 
这个工具只能拦助电脑小白，因为通过CMD命令也是可以把文件拷贝出来的。
