### ISSUE TITLE
应用程序错误

### ISSUE THREAD

**Issue by jasonXcoder** [Albert-W/Folder-locker#27]
![Snipaste_2021-04-01_17-12-18](https://user-images.githubusercontent.com/81746407/113271762-7020fc80-930d-11eb-97ea-be1acd024afe.png)

这是什么情况哦。

**Comment by jasonXcoder** [comment]
点击继续后，锁上了，如何就无法解锁了。

**Comment by Albert-W** [comment]
是由于软件安装目录的权限问题导致，已经在最新release中修复。
