### ISSUE TITLE
Folder Locker.exe意外被删除了，现在没法打开加密文件！

### ISSUE THREAD

**Issue by zhongsanyiyuan** [Albert-W/Folder-locker#31]
Folder Locker.exe意外被删除了，现在没法打开加密文件！提示：password is missing
怎么办？

**Comment by Noonehh** [comment]
密码保存在本机数据库，没有上传任何服务器。
删除软件会同时删除数据库，因此删除密码。
如果忘记密码：

如果，密码遗失，文件被锁，可以通过命令行工具重命名。
例如，你的文件夹为E：\ folder，就打开cmd命令窗口，执行如下命令

ren e:\folder.{2559a1f2-21d7-11d4-bdaf-00c04f60b9f0} new_folder
其中{2559a1f2-21d7-11d4-bdaf-00c04f60b9f0}不变，“ new_folder”替换为自己想要的文件名。

**Comment by Daidens** [comment]
> 密码保存在本机数据库，没有上传任何服务器。 删除软件会同时删除数据库，因此删除密码。 如果忘记密码：
> 
> 如果，密码遗失，文件被锁，可以通过命令行工具重命名。 例如，你的文件夹为E：\ folder，就打开cmd命令窗口，执行如下命令
> 
> ren e:\folder.{2559a1f2-21d7-11d4-bdaf-00c04f60b9f0} new_folder 其中{2559a1f2-21d7-11d4-bdaf-00c04f60b9f0}不变，“ new_folder”替换为自己想要的文件名。
![捕获](https://user-images.githubusercontent.com/64972876/152674462-6e2c56d9-6a8d-4eb0-95e3-c4598927e0fb.PNG)

用你说的这种办法，命令行提示找不到文件

**Comment by Albert-W** [comment]
可以说一下你的文件全路径，我帮你生成命令

**Comment by Albert-W** [comment]
在1.3.0 版本中，我增加了通用密码 Albert-W
