### ISSUE TITLE
老板您好,能不能把回收站的右键选项去掉啊, 优化一下

### ISSUE THREAD

**Issue by dayfan0810** [Albert-W/Folder-locker#8]
如果可以, 做一个由服务器下载更新的, 我有个阿里云最低配服务器,还有一年到期, 可以先给你用,做个收费版本也不错啊,5块钱一个.

**Comment by Albert-W** [comment]
是回收站的"folder locker"选项吗？
这个可以通过一些优化工具的右键添加删除功能调整。

**Comment by dayfan0810** [comment]
@Albert-W 好的
